
allowBuilds:
  '@parcel/watcher': true
  '@tsparticles/engine': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@iconify/json@2.2.508'
  - miniflare@5.20260730.0-alpha
  - wrangler@4.118.0
shellEmulator: true

trustPolicy: no-downgrade
